version: '3.8'

services:
  frontend:
    build: .
    container_name: autocampos-frontend
    ports:
      # Mapeia a porta configurável do host (default 8080) para a porta 80 do contêiner
      - "${FRONTEND_PORT:-3002}:80"
    restart: unless-stopped
    networks:
      - microservicos-net
    environment: # Adicione esta seção
      - REACT_APP_API_URL=http://web:8000 # O nome do serviço do seu backend é 'web'

networks:
  microservicos-net:
    external: true
